### ISSUE TITLE
Extension not working at all and gives error. 

### ISSUE THREAD

**Issue by im-jc** [ArturMoczulski/rollbar-php-magento2#3] opened 2018-08-10 06:13 UTC
Here are the points with errors.
1. Installation.
In your readme file following step is mentioned.
"Add rollbar-magento2 as a dependency in composer.json of your project and run composer update."
BUT what is the version? composer needs module version to be run command.

=> I have manually installed it by uploading files to app/code/Rollbar/Magento2.
Run both upgrade and compile commands successfully.

2. Added access token as following which is the correct way.
  ```
'rollbar' => 
  array (
    'access_token' => 'MY-TOKEN',
  )
```  

3. Now when i run site on frontend or in open magento admin then it gives HTTP ERROR 500.

Then i checked in logs and get the following error.
[E_ERROR] Uncaught Error: Class 'Rollbar\Magento2' not found in /chroot/home/app/code/Rollbar/Magento2/Plugin/InitPlugin.php:13

What to do now? Please provide support or upgrade your extension because magento standards are not maintained in xml files and any other files.

**Comment by ArturMoczulski** [comment] 2018-08-12 03:43
@im-jc I'm working on reproducing the problem and producing better documentation. Will post an update as soon as I can :) It might take me a while to reproduce, so in meantime I recommend:

1. Do install the extension through composer. I just added the repo to packagist so you should be able to do by adding: `rollbar/rollbar-magento2: *` to your `composer.json` requires.
2. Run `composer update` so composer regenerates your autloading files.
3. Add access token.
4. Test the result.

Can you check for me if this resolves the issue for you?

**Comment by im-jc** [comment] 2018-08-14 11:48
@ArturMoczulski I have installed it as per your suggestions.
It's working now. Thanks a lot

**Comment by im-jc** [comment] 2018-08-14 12:23
There is one more issue with logging:
Do i have to add \Rollbar\Rollbar::log everywhere? Becuase it is not logging magento2 exceptions in rollbar.
And when i tried to add follwing as your document suggest for testing.
```
Rollbar::log(Level::info(), 'Test info message');
throw new Exception('Test exception');

```
It gives following error and stops the script.
Error: Class 'Vendor\Custommodule\Controller\Account\Rollbar' not found.

How to fix this. Please provide solution.
Thanks

**Comment by ArturMoczulski** [comment] 2018-08-14 23:24
@im-jc Exceptions and errors should be logged automatically after you install and enable the extension. No manual logging needed. I understand you're experiencing problems with that? If so, make sure you followed all of the the steps in the installation doc and you did enable the extension in your magento setup. If you're having further issues, I'm happy to jump on a call and assist.

The error you're getting is due to a scoping mistake. You have to either use:

```php
<?php

use Rollbar\Rollbar;
use Rollbar\Payload\Level;
```

or a fully qualified class name:

```php
<?php

\Rollbar\Rollbar::log(
  \Rollbar\Payload\Level::info(),
  throw new \Exception('Test exception')
);
```

**Comment by im-jc** [comment] 2018-08-15 10:51
Okay. Great. Thanks a lot. :)

**Comment by im-jc** [comment] 2018-08-24 07:33
Hi!
I am trying to log using following code as per your suggetion.

```
<?php

\Rollbar\Rollbar::log(
  \Rollbar\Payload\Level::info(),
  throw new \Exception('Test exception')
);
```

But it gives me following error in magento log.
[E_CORE_ERROR] Exception thrown without a stack frame 

And in rollbar log it gives me following log.
 ParseError: syntax error, unexpected 'throw' (T_THROW)

What is the correct syntax?? Please let me know.
Thanks

**Comment by im-jc** [comment] 2018-08-24 07:33
Hi!
I am trying to log using following code as per your suggetion.

<?php

\Rollbar\Rollbar::log(
  \Rollbar\Payload\Level::info(),
  throw new \Exception('Test exception')
);

But it gives me following error in magento log.
[E_CORE_ERROR] Exception thrown without a stack frame 

And in rollbar log it gives me following log.
 ParseError: syntax error, unexpected 'throw' (T_THROW)

What is the correct syntax?? Please let me know.
Thanks

**Comment by ArturMoczulski** [comment] 2018-08-28 03:55
@im-jc what version of Magento and PHP are you using?

**Comment by im-jc** [comment] 2018-08-28 05:11
PHP Version 7.0.30
Magento Version 2.2.4

**Comment by ArturMoczulski** [comment] 2019-01-02 14:08
@im-jc in PHP you can't throw an exception and pass it as an argument at the same time.

The correct syntax in PHP is:

```
<?php

\Rollbar\Rollbar::log(
  \Rollbar\Payload\Level::info(),
  new \Exception('Test exception')
);
```

I'm closing the issue as there is no actual bug in the SDK here. Please comment if you're experiencing further issues and I will assist.

**Closed as completed by ArturMoczulski** 2019-01-02 14:08 UTC
Labels: question
